#<%=Rails.env%>:
development:
  adapter: mysql2
  database: smartpie
  username: root
  password:
  host: localhost
  pool: 5
  timeout: 5000
  reconnect: true
  # socket: /var/run/mysqld/mysqld.sock

  test:
    adapter: mysql2
    database: smartpie
    username: root
    password:
    host: localhost
    pool: 5
    timeout: 5000
    reconnect: true
    # socket: /var/run/mysqld/mysqld.sock

staging:
  adapter: mysql2
  database: smartpie
  username: root
  password:
  host: localhost
  pool: 5
  timeout: 5000
  reconnect: true
  # socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  database: smartpie
  username: root
  password:
  host: localhost
  pool: 5
  timeout: 5000
  reconnect: true
  # socket: /var/run/mysqld/mysqld.sock